// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// readFrame
Rcpp::S4 readFrame(Rcpp::S4 x, std::string sampleName, Rcpp::RObject j_obj, bool useExpr);
RcppExport SEXP ncdfFlow_readFrame(SEXP xSEXP, SEXP sampleNameSEXP, SEXP j_objSEXP, SEXP useExprSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< Rcpp::S4 >::type x(xSEXP );
        Rcpp::traits::input_parameter< std::string >::type sampleName(sampleNameSEXP );
        Rcpp::traits::input_parameter< Rcpp::RObject >::type j_obj(j_objSEXP );
        Rcpp::traits::input_parameter< bool >::type useExpr(useExprSEXP );
        Rcpp::S4 __result = readFrame(x, sampleName, j_obj, useExpr);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
