// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// toBitVec
Rcpp::RawVector toBitVec(Rcpp::LogicalVector indx);
RcppExport SEXP ncdfFlow_toBitVec(SEXP indxSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Rcpp::LogicalVector >::type indx(indxSEXP);
    __result = Rcpp::wrap(toBitVec(indx));
    return __result;
END_RCPP
}
// toLogical
Rcpp::LogicalVector toLogical(Rcpp::RawVector bytes);
RcppExport SEXP ncdfFlow_toLogical(SEXP bytesSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Rcpp::RawVector >::type bytes(bytesSEXP);
    __result = Rcpp::wrap(toLogical(bytes));
    return __result;
END_RCPP
}
// readFrame
Rcpp::S4 readFrame(Rcpp::S4 x, Rcpp::RObject i_obj, Rcpp::RObject j_obj, bool useExpr);
RcppExport SEXP ncdfFlow_readFrame(SEXP xSEXP, SEXP i_objSEXP, SEXP j_objSEXP, SEXP useExprSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Rcpp::S4 >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::RObject >::type i_obj(i_objSEXP);
    Rcpp::traits::input_parameter< Rcpp::RObject >::type j_obj(j_objSEXP);
    Rcpp::traits::input_parameter< bool >::type useExpr(useExprSEXP);
    __result = Rcpp::wrap(readFrame(x, i_obj, j_obj, useExpr));
    return __result;
END_RCPP
}
