# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Vec_subset_Rcpp <- function(input, i) {
    .Call('ncdfFlow_Vec_subset_Rcpp', PACKAGE = 'ncdfFlow', input, i)
}

readFrame <- function(x, i_obj, j_obj, useExpr) {
    .Call('ncdfFlow_readFrame', PACKAGE = 'ncdfFlow', x, i_obj, j_obj, useExpr)
}

